[update to 0.4.1] java: added RPCException for the internal error. and not to close all connections when it's thrown.
Hideyuki Tanaka (1):
      Haskell implementation

INADA Naoki (2):
      Add .gitignore for python.
      Python: Fix setup.py

Kazuki Ohta (21):
      java: checking client-side timeout by periodical timer.
      java: added RPCException for the internal error. and not to close all connections when it's thrown.
      java: add the test for reconnection (iteration of call->close).
      added javadocs. rename s/send/callAsync/ to follow the Ruby API.
      fixed the Java-RPC client bug, when receiving multiple messages at once.
      fixed the bug when server receives multiple messages through one connection.
      added MultiThreadServerTest.
      added CHANGES.txt for release 0.4.
      added copyright.
      added UDP tests to MultiThreadServerTest
      added source comments.
      java: remove unnecessary lock from UDPTransport.
      java: avoid nested lock in TCPSocket to prevent deadlock.
      java: remove unnecessary locks from TCPTransport.
      java: modify CHANGES.txt
      added README.md of MessagePack-RPC for Java
      java rpc version 0.4.0
      java: upgrade to netty 3.2.1.Final
      java: method lookup by Map, not linear search.
      java: version 0.4.1
      README.md: fixed old urls.

Ryan Phillips (1):
      cpp: add gitignore

UENISHI Kota (29):
      added initial code snippet.
      creating basic file skeleton for erlang
      can't send method to servr
      erlang: msgpack debug and initial msgpack-rpc client.
      erlang: added mp_client, a bit mp_server, a bit documentation.
      erlang: added some server works (OTP skeleton).
      erlang: mp_server_app should be a simple sample server.
      erlang: server should be plaggable
      erlang: adding pluggable server framework
      erlang: misc
      erlang: test app and msgpack-rpc framework
      erlang: Makefile mod.
      erlang: supervision tree seems working. TCP
      erlang: adding server callback frameworks.
      hello, msgpack-rpc
      erlang: added copyright notice. to be alpha release?
      erlang: a bit interface modifications
      erlang: a bit documentation.
      erlang: multiple sessions in client enabled
      erlang: adding automated test
      erlang:added some sample test cases.
      erlang: test automation
      erlang: simple installer added
      erlang: simple test
      erlang: updated to latest msgpack.erl - can't be distributed apart...
      erlang: oneshot test run.
      erlang: bugfix for case '-234' and other misc.
      erlang: first impl of nosuchmethoderror
      erlang: error doesn't cause connection failure

frsyuki (64):
      ruby: update rdoc
      ruby: future: doesn't wrap callback_handler but check on calling for backward compatibility
      cpp: bug fix: insert a future in reqtable before sending data
      idl: java: update
      idl: java: enum, const, exception
      cpp: redesigned
      ruby: prevents sending results twice
      cpp: UDP support
      cpp: UNIX socket support (halfway)
      cpp: rewrite address class; add unix tranposrt
      cpp: rewrite address class
      cpp: add caller::call_array and caller::notify_array
      idl: updates parser and rewrites AST impl.
      ruby: adds Session#call_apply and notify_apply
      ruby: updates dispatch mechanism
      idl: updates mplex.rb
      idl: rewrites ruby generator
      idl: rewrites cpp generator
      idl: rewrites ruby generator
      idl: rewrites cpp generator
      idl: splits service header into client and server
      idl: update Makefile
      idl: updates java generator
      idl: updates java generator
      idl: java: generates default value of user-defined class
      idl: java: generates equals() method
      idl: 'typedef' impl.
      idl: 'typedef' impl. 2
      idl: changes command name: mprpcgen -> msgpack-idl
      idl: update README.md
      idl: disables RPC service generation by default
      idl: version 0.1.0
      ruby: UDP transport: set sock.do_not_reverse_lookup = true on Ruby 1.9
      idl: fixes LOAD_PATH setting
      idl: shows messages on parse error
      idl: fixes require files
      cpp: adds missing transport_impl.h header
      ruby: rescues all errors on_readable not to stop event loop
      cpp: unix transport: undef 'unix'
      cpp: fixes install directory of transport/*.h headers
      ruby: fixes problem that future.get doesn't work in callback handler
      ruby: new exception mechanism
      ruby: adds MultiFuture
      ruby: adds MultiFuture#clear and clear_callback
      ruby: uses jeweler and Rakefile for packaging
      cpp: adds request::error(error, result)
      cpp: adds MSGPACK_RPC_VERSION constant
      cpp: version 0.2.0
      cpp: add high-load tests
      cpp: changes design of transport layer to avoid circular reference problem of shared_ptr
      cpp: graceful stopping of timer threads
      cpp: updates attack test cases
      cpp: fixes dgram_handler
      cpp: fixes dgram_handler
      cpp: updates attack test cases
      cpp: makes sure session_pool::get_session always pools new session
      cpp: test cases don't use 8080 port
      cpp: adds attack_callback test
      cpp: doesn't allocate memory from shared zone to avoid race condition
      cpp: increments library version-info
      cpp: increases default buffer size
      cpp: version 0.3.0
      ruby: fixes ConnectionTimeoutError::CODE
      ruby: version 0.4.1

h0x10 (3):
      php impl server/client
      Client.php call method fixed
      typo fixed